# Secrets configuration example
# Copy this file to secrets.yaml and fill in the values
# DO NOT commit secrets.yaml to version control

# Authentication configuration
auth:
  # JWT secret for signing tokens (generate a secure random string)
  jwt_secret: "replace_with_a_secure_random_string_at_least_32_chars_long"

# Media configuration
media:
  # YouTube API key for accessing YouTube Data API
  youtube_api_key: "your_youtube_api_key_here"
  # SoundCloud API key for accessing SoundCloud API
  # soundcloud_api_key: "your_soundcloud_api_key_here"

# Database configuration
database:
  # MongoDB connection credentials
  mongodb:
    # MongoDB connection URI with authentication
    uri: "mongodb://username:password@hostname:27017"
  
  # Redis connection credentials
  redis:
    # Redis password
    password: "your_redis_password_here"

# External services
services:
  # Email service configuration for notifications
  email:
    # SMTP server settings
    smtp_host: "smtp.example.com"
    smtp_port: 587
    smtp_username: "your_smtp_username"
    smtp_password: "your_smtp_password"
    from_email: "noreply@listenify.com"
  
  # Storage service configuration (if using external storage)
  storage:
    # S3-compatible storage credentials
    s3_access_key: "your_s3_access_key"
    s3_secret_key: "your_s3_secret_key"
    s3_bucket: "listenify-media"
    s3_region: "us-east-1"
    s3_endpoint: "https://s3.amazonaws.com"

# TLS certificates (if not using a certificate manager)
tls:
  # Certificate and key paths
  cert_file: "/path/to/certificate.pem"
  key_file: "/path/to/private_key.pem"